<?php
// Retrieve order
$_order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$_order->loadByIncrementId($orderId);

$sales_order = Mage::getModel('sales/order')->loadByIncrementId($orderId);

if ($sales_order->getCustomerId() == '') {

//guests
    $first_name = $sales_order->getBillingAddress()->getFirstname();
    $last_name = $sales_order->getBillingAddress()->getLastname();
    $email = $sales_order->getBillingAddress()->getEmail();
    $phone = $sales_order->getBillingAddress()->getTelephone();
    $address = $sales_order->getBillingAddress()->getStreet();
    $city = $sales_order->getBillingAddress()->getCity();
    $country = $sales_order->getBillingAddress()->getCountry();

} else {

//registered users
    $customer = Mage::getModel('customer/customer')->load($sales_order->getCustomerId());
    $first_name = $customer->getDefaultBillingAddress()->getFirstname();
    $last_name = $customer->getDefaultBillingAddress()->getLastname();
    $email = $customer->getEmail();
    $phone = $customer->getDefaultBillingAddress()->getTelephone();
    $address = $customer->getDefaultBillingAddress()->getStreet();
    $city = $customer->getDefaultBillingAddress()->getCity();
    $country = $customer->getDefaultBillingAddress()->getCountry();

}


$base_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$merchant_id = Mage::getStoreConfig('payment/directpay/merchant_id');
$apiKey = Mage::getStoreConfig('payment/directpay/secret_key');
$privateKey = Mage::getStoreConfig('payment/directpay/private_key');
$test_mode = Mage::getStoreConfig('payment/directpay/test_mode');
$currency = Mage::app()->getStore()->getCurrentCurrencyCode();

if ($test_mode == 1) {
    $checkout_url = "https://testpay.directpay.lk";
} else if ($test_mode == 0) {
    $checkout_url = "https://pay.directpay.lk";
}


$items = $sales_order->getAllVisibleItems();
$item_names = array();
$item_count = 1;
foreach ($items as $i):
    $item_names[] = $i->getName();
    $optional_params .=
        '
		   <input type="hidden" name="item_name_' . $item_count . '" value="' . $i->getName() . '">
		   <input type="hidden" name="item_number_' . $item_count . '" value="' . $i->getProductId() . '">
		   <input type="hidden" name="amount_' . $item_count . '" value="' . number_format((float)$i->getPrice(), 2, '.', '') . '">
		   <input type="hidden" name="quantity_' . $item_count . '" value="' . round($i->getData('qty_ordered')) . '">
		  ';
    $item_count++;
endforeach;


$amount = number_format((float)$_order->getBaseGrandTotal(), 2, '.', '');
$item_names = implode(", ", $item_names);


$pluginName = "Magento";
$pluginVersion = 1.9;

$success_url = $base_url . "directpay/payment/response";

$returnUrl = $success_url;
$cancelUrl = $base_url . "directpay/payment/cancel";
$reponseUrl = $success_url;

//data string concat order
$dataString = $merchant_id .
    $amount .
    $currency .
    $pluginName .
    $pluginVersion .
    $returnUrl .
    $cancelUrl .
    $orderId .
    $orderId .
    $first_name .
    $last_name .
    $email .
    $item_names .
    $apiKey .
    $reponseUrl;


$signature = null;

$pkeyid = openssl_pkey_get_private($privateKey);

//Generate signature
$signResult = openssl_sign($dataString, $signature, $pkeyid, OPENSSL_ALGO_SHA256);
//Base64 encode the signature
$signature = base64_encode($signature);
//Free the key from memory
openssl_free_key($pkeyid);


?>
<form name="directpaycheckoutform" method="post" action="<?php echo $checkout_url; ?>">
    <input type="hidden" name="_mId" value="<?php echo $merchant_id; ?>">
    <input type="hidden" name="api_key" value="<?php echo $apiKey; ?>">
    <input type="hidden" name="_returnUrl" value="<?php echo $returnUrl; ?>">
    <input type="hidden" name="_cancelUrl" value="<?php echo $cancelUrl; ?>">
    <input type="hidden" name="_responseUrl" value="<?php echo $reponseUrl; ?>">
    <input type="hidden" name="_amount" value="<?php echo $amount; ?>">
    <input type="hidden" name="_currency" value="<?php echo $currency; ?>">
    <input type="hidden" name="_reference" value="<?php echo $orderId; ?>">
    <input type="hidden" name="_orderId" value="<?php echo $orderId; ?>">
    <input type="hidden" name="_pluginName" value="<?php echo $pluginName; ?>">
    <input type="hidden" name="_pluginVersion" value="<?php echo $pluginVersion; ?>">
    <input type="hidden" name="_description" value="<?php echo $item_names; ?>">
    <input type="hidden" name="_firstName" value="<?php echo $first_name; ?>">
    <input type="hidden" name="_lastName" value="<?php echo $last_name; ?>">
    <input type="hidden" name="_email" value="<?php echo $email; ?>">
    <input type="hidden" name="signature" value="<?php echo $signature; ?>">


    <?php echo $optional_params; ?>
</form>
<script type="text/javascript">
    document.directpaycheckoutform.submit();
</script>